
PYDIR=$(HOME)/anaconda3/bin

all:

run:all

server:
	sudo $(PYDIR)/python server.py
	# python server.py

client:
	sudo $(PYDIR)/python client.py
	# python client.py

ipython:
	sudo $(PYDIR)/ipython

clean:
	rm -rf *.pyc *.ini